"""Add Wallet model

Revision ID: e7e4ae6d091d
Revises: 
Create Date: 2024-09-25 23:58:16.470992

"""
from decimal import Decimal
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e4ae6d091d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
                    sa.Column('amount', sa.Numeric(precision=10, scale=2),
                              nullable=False, default=Decimal('0.0')),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.CheckConstraint(
                        'amount >= 0.0', name='check_amount_positive'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    # ### end Alembic commands ###
